version: '3.8'
networks:
  mired:
    ipam:
      config:
        - subnet: 182.28.0.0/16
          gateway: 182.28.0.1
services:
  db:
    image: bitnami/mongodb:latest
    container_name: mongo_DB
    networks:
      mired:
        ipv4_address: 182.28.0.11
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=examplepassword
    expose:
      - 27017

  app-tutorials:
    image: apedlop042/tutorials2025:2
    container_name: tutorialsapp
    networks:
      mired:
        ipv4_address: 182.28.0.12
    expose:
      - 8098
    ports:
      - "8098:8098"
    depends_on:
      - db
    environment:
      - DB_HOST=mongo_DB
      - DB_PORT=27017
      - DB_USERNAME=root
      - DB_PASSWORD=examplepassword
    # Si la aplicación necesita esperar a MongoDB antes de arrancar
    entrypoint: ["sh", "-c", "sleep 10 && /app/start.sh"]
